### ISSUE TITLE
Migration to Webpack 5 awaited

### ISSUE THREAD

**Issue by tomtom94** [tomtom94/react-easy-ssr#1]
There is just one plugin awaited to be compatible with webpack 5, issue in standby.

https://github.com/gregberge/loadable-components/issues/636

**Comment by mustaqball** [comment]
I think you can already migrate to webpack v5

**Comment by tomtom94** [comment]
Next winter 2021/2022 I'll do this.

Modules and plugins would be more reliable with webpack 5.

Right now this would just bring you headaches and I am missing of paracetamol.

**Comment by tomtom94** [comment]
@arman-mukatov I just achieved a beta version with webpack 5

Checkout the MR https://github.com/tomtom94/react-easy-ssr/pull/2

Wait before I merge into master branch
